"use client";
import { useRef, useState } from "react";
type Subject = { id: string; name_uk: string };
export function TutorOnboarding({ subjects }: { subjects: Subject[] }) {
  const [step, setStep] = useState(1); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const formRef = useRef<HTMLFormElement>(null);
  async function save(submit: boolean) {
    if (!formRef.current) return; setBusy(true); setError(null); const form = new FormData(formRef.current);
    const payload = { firstName: form.get("firstName"), lastName: form.get("lastName"), dateOfBirth: form.get("dateOfBirth"), headline: form.get("headline"), biography: form.get("biography"), city: form.get("city"), teachingFormat: form.get("teachingFormat"), experienceYears: form.get("experienceYears"), nmtPreparation: form.get("nmtPreparation") === "on", subjectIds: form.getAll("subjectIds"), phone: form.get("phone") || undefined, priceUah: form.get("priceUah") || undefined, priceMinutes: form.get("priceMinutes") || undefined };
    const draft = await fetch("/api/tutor/draft", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await draft.json(); if (!draft.ok) { setError(data.error ?? "Не вдалося зберегти чернетку."); setBusy(false); return; }
    const photo = form.get("photo"); if (photo instanceof File && photo.size) { const upload = new FormData(); upload.set("file", photo); upload.set("tutorId", data.tutorId); const response = await fetch("/api/upload", { method: "POST", body: upload }); if (!response.ok) { setError((await response.json()).error ?? "Не вдалося завантажити фото."); setBusy(false); return; } }
    if (submit) { const response = await fetch("/api/tutor/submit", { method: "POST" }); if (!response.ok) { setError((await response.json()).error ?? "Не вдалося подати профіль."); setBusy(false); return; } } setSaved(true); setBusy(false);
  }
  return <form ref={formRef} className="card stack" onSubmit={(event) => { event.preventDefault(); void save(false); }}>
    <div className="pills"><span className="pill">1. Про вас</span><span className="pill">2. Предмети</span><span className="pill">3. Контакти й ціна</span></div><h2>{step === 1 ? "Створіть профіль репетитора" : step === 2 ? "Що ви викладаєте" : "Контакти та публікація"}</h2>{error && <p className="error" role="alert">{error}</p>}{saved && <p className="notice">Чернетку збережено. Після подання профіль перевірить модерація.</p>}
    <section hidden={step !== 1} className="stack"><div className="form-grid"><label>Ім’я<input name="firstName" required placeholder="Анна" /></label><label>Прізвище<input name="lastName" required placeholder="Коваль" /></label></div><label>Дата народження<input name="dateOfBirth" type="date" required /><span>Приватна. Профіль доступний з 14 років.</span></label><label>Коротко про себе<input name="headline" minLength={10} required placeholder="Пояснюю математику просто й без стресу" /></label><label>Біографія<textarea name="biography" minLength={80} required placeholder="Розкажіть про досвід, підхід і кому ви допомагаєте…" /></label><div className="form-grid"><label>Формат<select name="teachingFormat" defaultValue="online"><option value="online">Онлайн</option><option value="offline">Офлайн</option><option value="hybrid">Онлайн та офлайн</option></select></label><label>Місто<input name="city" placeholder="Київ" /></label><label>Років досвіду<input name="experienceYears" type="number" min="0" defaultValue="0" /></label></div><label><input type="checkbox" name="nmtPreparation" /> Готую до НМТ</label></section>
    <fieldset hidden={step !== 2}><legend>Оберіть до 3 предметів</legend><div className="pills">{subjects.map((subject) => <label className="pill" key={subject.id}><input type="checkbox" name="subjectIds" value={subject.id} /> {subject.name_uk}</label>)}</div></fieldset>
    <section hidden={step !== 3} className="stack"><div className="notice">Фото приватне до схвалення. Допустимі JPEG, PNG або WebP до 5 МБ.</div><label>Головне фото<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" /></label><label>Телефон для публікації<input name="phone" type="tel" placeholder="+380 67 123 45 67" /></label><div className="form-grid"><label>Ціна, грн<input name="priceUah" type="number" min="1" placeholder="300" /></label><label>Тривалість, хв<input name="priceMinutes" type="number" min="15" placeholder="60" /></label></div></section>
    <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><button className="button" type="button" disabled={step === 1} onClick={() => setStep(step - 1)}>Назад</button>{step < 3 ? <button className="button primary" type="button" onClick={() => setStep(step + 1)}>Далі</button> : <button className="button primary" type="button" disabled={busy} onClick={() => void save(true)}>{busy ? "Збереження…" : "Подати на перевірку"}</button>}</div>
  </form>;
}
