import { notFound } from "next/navigation";
import { FavoriteButton } from "@/components/favorite-button";
import { ReviewForm } from "@/components/review-form";
import { priceLabel } from "@/lib/format";
import { requireUser } from "@/lib/auth";

export default async function TutorPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const { supabase, user } = await requireUser();
  const { data: tutor } = await supabase.from("tutor_profiles").select("id,slug,headline,biography,teaching_style,city,teaching_format,experience_years,education,student_levels,nmt_preparation,profiles(first_name,last_name),tutor_subjects(subjects(name_uk)),tutor_photos(bucket_path,is_primary),tutor_pricing(kind,amount_uah,duration_minutes,group_size,note,is_primary),tutor_achievements(title,description,is_verified),tutor_contacts(id,kind,label,value),reviews(id,rating,body,created_at,profiles:author_id(first_name,last_name))").eq("slug", slug).eq("status", "approved").maybeSingle();
  if (!tutor) notFound();
  const { data: favorite } = await supabase.from("favorites").select("tutor_id").eq("tutor_id", tutor.id).eq("user_id", user.id).maybeSingle();
  const primary = tutor.tutor_photos.find((photo) => photo.is_primary); const { data: signed } = primary ? await supabase.storage.from("tutor-media-approved").createSignedUrl(primary.bucket_path, 60 * 10) : { data: null };
  const name = [tutor.profiles[0]?.first_name, tutor.profiles[0]?.last_name].filter(Boolean).join(" ");
  const average = tutor.reviews.length ? (tutor.reviews.reduce((sum, review) => sum + review.rating, 0) / tutor.reviews.length).toFixed(1) : "Новий";
  return <div className="details"><article className="stack"><div className="card photo">{signed?.signedUrl ? <img className="portrait" src={signed.signedUrl} alt={`Фото ${name}`} style={{ objectFit: "cover", width: "100%" }} /> : <div className="portrait">◉</div>}<div className="card-body"><p className="muted">{tutor.teaching_format === "online" ? "Онлайн" : tutor.city}</p><h1 style={{ fontSize: 40 }}>{name}</h1><div className="pills">{tutor.tutor_subjects.map(({ subjects }) => <span className="pill" key={subjects[0]?.name_uk}>{subjects[0]?.name_uk}</span>)}</div><p>★ {average} {tutor.reviews.length ? `(${tutor.reviews.length} відгуків)` : ""}</p><p>{tutor.headline}</p></div></div><section className="card"><h2>Про мене</h2><p>{tutor.biography}</p><h2>Підхід до навчання</h2><p>{tutor.teaching_style || "Підхід обговорюється індивідуально."}</p></section><section className="card"><h2>Досвід та освіта</h2><p>{tutor.experience_years ?? 0} років досвіду</p><p>{tutor.education || "Освіта не вказана"}</p>{tutor.nmt_preparation && <span className="pill">Підготовка до НМТ</span>}</section>{tutor.tutor_achievements.length > 0 && <section className="card"><h2>Досягнення</h2>{tutor.tutor_achievements.map((item) => <p key={item.title}>{item.is_verified && "✓ "}<strong>{item.title}</strong>{item.description && ` — ${item.description}`}</p>)}</section>}<section className="stack"><h2>Відгуки</h2>{tutor.reviews.map((review) => <article className="card" key={review.id}><strong>{review.profiles[0]?.first_name ?? "Користувач"} · ★ {review.rating}</strong><p>{review.body}</p></article>)}<ReviewForm tutorId={tutor.id} /></section></article><aside className="card sticky stack"><h2>{priceLabel(tutor.tutor_pricing.find((item) => item.is_primary) ?? tutor.tutor_pricing[0])}</h2><FavoriteButton tutorId={tutor.id} initial={Boolean(favorite)} /><h3>Зв’язатися</h3>{tutor.tutor_contacts.length ? tutor.tutor_contacts.map((contact) => <a className="button" key={contact.id} href={contact.kind === "phone" ? `tel:${contact.value}` : contact.value} target={contact.kind === "phone" ? undefined : "_blank"} rel="noreferrer">{contact.label || (contact.kind === "phone" ? "Подзвонити" : contact.kind)}</a>) : <p className="muted">Репетитор ще не додав контакти.</p>}</aside></div>;
}
